minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

packages:
  - playground
  - docs
  - packages/*
  - examples/*

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
