/**
 * Regenerates `src/collections.ts` from the Iconify API.
 *
 * Only the prefixes are kept, so the list stays a couple of kilobytes and the
 * package needs no runtime dependency to know about every collection.
 *
 * Run with `pnpm update-collections`.
 */
import { writeFile } from 'node:fs/promises'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const endpoint = 'https://api.iconify.design/collections'
const output = fileURLToPath(new URL('../src/collections.ts', import.meta.url))

const response = await fetch(endpoint)
if (!response.ok) {
  throw new Error(`Failed to fetch ${endpoint}: ${response.status} ${response.statusText}`)
}

const prefixes = Object.keys(await response.json() as Record<string, unknown>).sort()
if (!prefixes.length) {
  throw new Error(`No collections returned by ${endpoint}`)
}

await writeFile(output, `// Generated by \`pnpm update-collections\`, do not edit.
// Source: ${endpoint}

/**
 * Every icon collection prefix known to Iconify.
 *
 * Pass it as \`collections\` to match all of them, including the two letter
 * prefixes \`defaultIconCollections\` leaves out.
 */
export const allIconCollections: string[] = [
${prefixes.map(prefix => `  '${prefix}',`).join('\n')}
]
`)

process.stdout.write(`Wrote ${prefixes.length} collections to ${output}\n`)
